# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    hello_message: 'hello from message'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

        bind:
            $message: '%hello_message%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # this can be replaced by binding the $message to the %hello_message% parameter
    #App\Service\Greeting:
    #    arguments:
    #        $message: '%hello_message%'
    #       this is fetched from the parameter definition above
    #       $message: 'Hello from service'

    # dependency injection without autowiring (injects each dependency into the service)
    # App\Controller\BlogController: ['@App\Service\Greeting', '@App\Service\VeryBadDesign']
    # App\Service\Greeting: ['@monolog.logger']

    # make public only the service you need (don't make public all of them)
    app.greeting:
        public: true
        alias: App\Service\Greeting

    App\Twig\AppExtension:
        arguments:
            $locale: '%locale%'

    App\EventListener\LikeNotificationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
